apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootcrud-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springbootcrud
  template:
    metadata:
      labels:
        app: springbootcrud
    spec:
      containers:
        - name: springbootcrud-container
          image: registry.digitalocean.com/digitaloceanregistry/springbootcrud:latest
          ports:
            - containerPort: 8080